global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8765' ]
  - job_name: 'catalog-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:18080' ]